CREATE OR REPLACE USER 'admin'@'%' IDENTIFIED BY 'adminpassword';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

DROP SCHEMA IF EXISTS ahadpos3; CREATE SCHEMA ahadpos3 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;